# Generated by Django 4.2.7 on 2023-11-11 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=100)),
                ('inn', models.CharField(max_length=10)),
                ('telephone', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id_contract', models.AutoField(primary_key=True, serialize=False)),
                ('info', models.TextField()),
                ('creation', models.DateField()),
                ('execution', models.DateField(blank=True, null=True)),
                ('amount', models.IntegerField()),
                ('id_client', models.ForeignKey(db_column='id_client', on_delete=django.db.models.deletion.CASCADE, to='wdb.client')),
            ],
            options={
                'db_table': 'contract',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id_employee', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id_factory', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('info', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'factory',
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id_parameter', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'parameter',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id_post', models.AutoField(primary_key=True, serialize=False)),
                ('post', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'post',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id_specialization', models.AutoField(primary_key=True, serialize=False)),
                ('specialization', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'specialization',
            },
        ),
        migrations.CreateModel(
            name='StateContract',
            fields=[
                ('id_state_contract', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'state_contract',
            },
        ),
        migrations.CreateModel(
            name='TypeEquipment',
            fields=[
                ('id_type_equipment', models.AutoField(primary_key=True, serialize=False)),
                ('type_equipment', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'type_equipment',
            },
        ),
        migrations.CreateModel(
            name='TypeWorkshop',
            fields=[
                ('id_type_workshop', models.AutoField(primary_key=True, serialize=False)),
                ('type_workshop', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'type_workshop',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id_warehouse', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('workload', models.IntegerField()),
                ('info', models.TextField()),
            ],
            options={
                'db_table': 'warehouse',
            },
        ),
        migrations.CreateModel(
            name='EmployeeDriver',
            fields=[
                ('id_employee', models.OneToOneField(db_column='id_employee', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wdb.employee')),
                ('license', models.CharField(max_length=12)),
                ('end_of_action', models.DateField()),
            ],
            options={
                'db_table': 'employee_driver',
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id_workshop', models.AutoField(primary_key=True, serialize=False)),
                ('id_factory', models.ForeignKey(db_column='id_factory', on_delete=django.db.models.deletion.CASCADE, to='wdb.factory')),
                ('id_type_workshop', models.ForeignKey(db_column='id_type_workshop', on_delete=django.db.models.deletion.CASCADE, to='wdb.typeworkshop')),
            ],
            options={
                'db_table': 'workshop',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('arrival', models.DateField()),
                ('id_contract', models.ForeignKey(blank=True, db_column='id_contract', null=True, on_delete=django.db.models.deletion.CASCADE, to='wdb.contract')),
                ('id_warehouse', models.ForeignKey(db_column='id_warehouse', on_delete=django.db.models.deletion.CASCADE, to='wdb.warehouse')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id_material', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('arrival', models.DateField()),
                ('id_workshop', models.ForeignKey(db_column='id_workshop', on_delete=django.db.models.deletion.CASCADE, to='wdb.workshop')),
            ],
            options={
                'db_table': 'material',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id_equipment', models.AutoField(primary_key=True, serialize=False)),
                ('id_type_equipment', models.ForeignKey(db_column='id_type_equipment', on_delete=django.db.models.deletion.CASCADE, to='wdb.typeequipment')),
                ('id_workshop', models.ForeignKey(db_column='id_workshop', on_delete=django.db.models.deletion.CASCADE, to='wdb.workshop')),
            ],
            options={
                'db_table': 'equipment',
            },
        ),
        migrations.CreateModel(
            name='EntryParameter',
            fields=[
                ('id_entry_parameter', models.AutoField(primary_key=True, serialize=False)),
                ('date_entry', models.DateTimeField()),
                ('value', models.TextField()),
                ('id_equipment', models.ForeignKey(db_column='id_equipment', on_delete=django.db.models.deletion.CASCADE, to='wdb.equipment')),
                ('id_parameter', models.ForeignKey(db_column='id_parameter', on_delete=django.db.models.deletion.CASCADE, to='wdb.parameter')),
            ],
            options={
                'db_table': 'entry_parameter',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='id_post',
            field=models.ForeignKey(db_column='id_post', on_delete=django.db.models.deletion.CASCADE, to='wdb.post'),
        ),
        migrations.AddField(
            model_name='contract',
            name='id_employee',
            field=models.ForeignKey(db_column='id_employee', on_delete=django.db.models.deletion.CASCADE, to='wdb.employee'),
        ),
        migrations.AddField(
            model_name='contract',
            name='id_state_contract',
            field=models.ForeignKey(db_column='id_state_contract', on_delete=django.db.models.deletion.CASCADE, to='wdb.statecontract'),
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id_transportation', models.AutoField(primary_key=True, serialize=False)),
                ('dispatch', models.DateField()),
                ('arrival', models.DateField()),
                ('info', models.TextField(blank=True, null=True)),
                ('id_employee', models.ForeignKey(db_column='id_employee', on_delete=django.db.models.deletion.CASCADE, to='wdb.employee')),
                ('id_factory', models.ForeignKey(db_column='id_factory', on_delete=django.db.models.deletion.CASCADE, to='wdb.factory')),
                ('id_product', models.ForeignKey(db_column='id_product', on_delete=django.db.models.deletion.CASCADE, to='wdb.product')),
                ('id_warehouse', models.ForeignKey(db_column='id_warehouse', on_delete=django.db.models.deletion.CASCADE, to='wdb.warehouse')),
            ],
            options={
                'db_table': 'transportation',
                'unique_together': {('id_transportation', 'id_product', 'id_warehouse', 'id_factory')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeWarehouseman',
            fields=[
                ('id_employee', models.OneToOneField(db_column='id_employee', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wdb.employee')),
                ('id_warehouse', models.ForeignKey(blank=True, db_column='id_warehouse', null=True, on_delete=django.db.models.deletion.CASCADE, to='wdb.warehouse')),
            ],
            options={
                'db_table': 'employee_warehouseman',
            },
        ),
        migrations.CreateModel(
            name='EmployeeMetallurgist',
            fields=[
                ('id_employee', models.OneToOneField(db_column='id_employee', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wdb.employee')),
                ('id_factory', models.ForeignKey(blank=True, db_column='id_factory', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wdb.factory')),
                ('id_specialization', models.ForeignKey(blank=True, db_column='id_specialization', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wdb.specialization')),
            ],
            options={
                'db_table': 'employee_metallurgist',
            },
        ),
    ]
